// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LaunchContract$Type } from "./LaunchContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LaunchContract"]: LaunchContract$Type;
    ["contracts/launchpad.sol:LaunchContract"]: LaunchContract$Type;
  }
}
