// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC20$Type } from "./IERC20";
import { Vault3$Type } from "./Vault3";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC20"]: IERC20$Type;
    ["Vault3"]: Vault3$Type;
    ["contracts/Vault3.sol:IERC20"]: IERC20$Type;
    ["contracts/Vault3.sol:Vault3"]: Vault3$Type;
  }
}
