// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC20$Type } from "./IERC20";
import { Vault2$Type } from "./Vault2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC20"]: IERC20$Type;
    ["Vault2"]: Vault2$Type;
    ["contracts/Vault2.sol:IERC20"]: IERC20$Type;
    ["contracts/Vault2.sol:Vault2"]: Vault2$Type;
  }
}
