// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC20$Type } from "./IERC20";
import { Vault1$Type } from "./Vault1";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC20"]: IERC20$Type;
    ["Vault1"]: Vault1$Type;
    ["contracts/Vault1.sol:IERC20"]: IERC20$Type;
    ["contracts/Vault1.sol:Vault1"]: Vault1$Type;
  }
}
